version: '3.7'
services:
  web1:
    build: ./webapp
    # image: glidematrix/nodeapp
    container_name: web1
    volumes:
      - ./webapp:/usr/src/app
    #   - /usr/src/app/node_modules
    environment:
      appName: "web1"
    expose:
     - 5000
    # ports:
    #   - "5000:5000"
  web2:
    build: ./webapp
    container_name: web2
    volumes:
      - ./webapp:/usr/src/app
    environment:
      appName: "web2"
    expose:
     - 5000
    # ports:
    #   - "5001:5000"
  web3:
    build: ./webapp
    container_name: web3
    volumes:
      - ./webapp:/usr/src/app
    environment:
      appName: "web3"
    expose:
     - 5000

  haproxy:
    build: ./haproxy
    # image: glidematrix/haproxy
    container_name: haproxy
    volumes:
     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
     - ./haproxy/webapp.pem:/usr/src/webapp.pem
    links:
     - web1
     - web2
    ports:
     - "80:80"
     - "443:443"
     - "8404:8404"


# docker-compose exec haproxy bash